version: "3"

services:

  service-1:
    image: markoff/service-1
    container_name: svc-1
    ports:
      - "8081:8081"
    depends_on:
          - service-2

  service-2:
    image: markoff/service-2
    container_name: svc-2
    ports:
      - "8082:8082"
    depends_on:
      - db

  db:
    image: mysql
    container_name: svc-mysql
    ports:
      - "3306:3306"
    environment: # passwords are for demo purposes, should be passed in
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user

  jenkins:
      image: jenkins/jenkins:lts
      container_name: svc-jenkins
      ports:
        - "8090:8080"
        - "50000:50000"
      volumes:
        - jenkins_home2:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      command: >
        bash -c "apt-get -qq update
        && apt-get -qq -y install curl
        && curl -sSL https://get.docker.com/ | sh
        && curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        && chmod +x /usr/local/bin/docker-compose
        && docker-compose --version
        && usermod -aG docker jenkins
        && /usr/local/bin/jenkins.sh"
      user: root

volumes:
  jenkins_home2: