apiVersion: v1
kind: Service
metadata:
# Unique key of the Service instance
  name: svc-1
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    svc: service-1
  type: LoadBalancer
