apiVersion: v1
kind: Service
metadata:
# Unique key of the Service instance
  name: svc-2
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    svc: service-2
  type: ClusterIP
