apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f ..\..\docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8080
  - name: "50000"
    port: 50000
    targetPort: 50000
  selector:
    io.kompose.service: jenkins
status:
  loadBalancer: {}
