apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f ..\..\docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: service-2
  name: service-2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: service-2
    spec:
      containers:
      - env:
        - name: DATASOURCE_PASSWORD
          value: user
        - name: DATASOURCE_URL
          value: jdbc:mysql://svc-mysql:3306/testdb
        - name: DATASOURCE_USERNAME
          value: user
        image: markoff/service-2
        name: svc-2
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
